# Run Tests

name: UQPCE Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

  workflow_dispatch:
    inputs:
      uqpce_pixi:
        type: boolean
        description: "Run tests using uqpce's pixi environment"
        required: false
        default: true

jobs:

  test_uqpce_pixi:
    runs-on: ${{ matrix.runs-on }}

    defaults:
      run:
        shell: bash

    timeout-minutes: 90

    strategy:
      fail-fast: false
      matrix:
        include:
          - pixi-env: default
            runs-on: ubuntu-latest
          - pixi-env: default
            runs-on: macos-latest
          - pixi-env: default
            runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          environments: ${{ matrix.pixi-env }}

      - name: Display run details
        run: |
          echo "============================================================="
          echo "Run #${GITHUB_RUN_NUMBER}"
          echo "Testing: ${GITHUB_REPOSITORY}"
          echo "Pixi environment: ${{ matrix.pixi-env }}"
          echo "OS: ${{ matrix.runs-on }}"
          echo "============================================================="

      - name: Run tests
        run: |
          pixi run -e ${{ matrix.pixi-env }} python -m unittest discover uqpce "test*.py"
